// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyurgvfqakbbwpaxvekm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5dXJndmZxYWtiYndwYXh2ZWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTQxMzAsImV4cCI6MjA3MzgzMDEzMH0.CAnRctDQG7TjScYT4y2JUfbz2aOgOc3n2pum1cJcj7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});